# Generated by Django 5.0.1 on 2024-01-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comments_parent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='have_replies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comments',
            name='is_reply',
            field=models.BooleanField(default=False),
        ),
    ]
